import React, { useState, useEffect } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { data } from "../facts/facts_copy.ts";
import styles from "../styles/Home.module.css";
import Image from "next/image";

const Home: NextPage = () => {
  const [numTabs, setNumTabs] = useState(0);
  const [text, setText] = useState("");
  const [fact, setFact] = useState("");
  const [imgSrc, setImgSrc] = useState("");

  const fetchData = async () => {
    const response = await fetch("/api/hello");
    const result = (await response.json()).tabs_today;
    setNumTabs(result);
  };

  const reset = async () => {
    await fetch("/api/reset");
    fetchData();
  };

  useEffect(() => {
    fetchData();
  }, []);

  useEffect(() => {
    setText(`You opened ${numTabs} tab${numTabs != 1 ? "s" : ""} today`);
    if (numTabs > 0) {
      const factList = data[numTabs] ?? [];
      if (factList.length > 0) {
        setFact(factList[Math.floor(Math.random() * factList.length)]);
      } else {
        setFact(
          "please stop opening more tabs",
        );
      }
    }

    if (numTabs === 5) {
      setImgSrc("/fiveguys.png");
    } else {
      setImgSrc("");
    }
  }, [numTabs]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Close Your Tabs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{text}</h1>
        <h4 className={styles.fact}>{fact}</h4>
        {imgSrc && (
          <Image
            className={styles.promo}
            src={imgSrc}
            width="512"
            height="512"
          />
        )}
        <button className={styles.reset} onClick={reset}>
          Reset
        </button>
      </main>
    </div>
  );
};

export default Home;
